workspace:
  base: /go/src
  path: github.com/appleboy/drone-facebook

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  lint:
    image: appleboy/golang-testing
    pull: true
    group: golang
    commands:
      - make vet
      - make lint

  test:
    image: appleboy/golang-testing
    pull: true
    group: golang
    secrets: [ fb_page_token, fb_verify_token ]
    commands:
      - make test
      - make coverage

  build:
    image: appleboy/golang-testing
    pull: true
    group: golang
    commands:
      - make docker_build

  release:
    image: appleboy/golang-testing
    pull: true
    environment:
      TAGS: netgo
      GOPATH: /srv/app
    commands:
      - make release
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  github:
    image: plugins/github-release
    api_key: ${GITHUB_RELEASE_API_KEY}
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]
